var searchData=
[
  ['dal_0',['DAL',['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html',1,'CodereTvmaze.DAL'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html',1,'CodereTvmaze.DAL'],['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md182',1,'CodereTvmaze.DAL'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md317',1,'CodereTvmaze.DAL']]],
  ['databaseconnection_1',['DatabaseConnection',['../class_codere_tvmaze_1_1_d_a_l_1_1_database_connection.html',1,'CodereTvmaze::DAL']]],
  ['databaseconnection_20tt_20type_20tt_2',['DatabaseConnection tt type tt',['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md198',1,'DatabaseConnection &lt;tt&gt;type&lt;/tt&gt;'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md333',1,'DatabaseConnection &lt;tt&gt;type&lt;/tt&gt;']]],
  ['day_20pos_20tt_20method_20tt_3',['day pos tt method tt',['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md289',1,'AddSchedule(connection,mainInfoId,time,day,pos) &lt;tt&gt;method&lt;/tt&gt;'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md424',1,'AddSchedule(connection,mainInfoId,time,day,pos) &lt;tt&gt;method&lt;/tt&gt;']]],
  ['deletemaininfogenres_4',['DeleteMainInfoGenres',['../class_codere_tvmaze_1_1_d_a_l_1_1_genre.html#a0a0ae3904fb3254251414f9feae99704',1,'CodereTvmaze::DAL::Genre']]],
  ['deletemaininfogenres_20connection_20maininfoid_20tt_20method_20tt_5',['DeleteMainInfoGenres connection mainInfoId tt method tt',['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md238',1,'DeleteMainInfoGenres(connection,mainInfoId) &lt;tt&gt;method&lt;/tt&gt;'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md373',1,'DeleteMainInfoGenres(connection,mainInfoId) &lt;tt&gt;method&lt;/tt&gt;']]],
  ['deletemaininfoschedule_6',['DeleteMainInfoSchedule',['../class_codere_tvmaze_1_1_d_a_l_1_1_schedule.html#a7be8b263b6e47be76ef64703ebcb0bad',1,'CodereTvmaze::DAL::Schedule']]],
  ['deletemaininfoschedule_20connection_20maininfoid_20tt_20method_20tt_7',['DeleteMainInfoSchedule connection mainInfoId tt method tt',['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md292',1,'DeleteMainInfoSchedule(connection,mainInfoId) &lt;tt&gt;method&lt;/tt&gt;'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md427',1,'DeleteMainInfoSchedule(connection,mainInfoId) &lt;tt&gt;method&lt;/tt&gt;']]],
  ['dispose_8',['Dispose',['../class_codere_tvmaze_1_1_d_a_l_1_1_database_connection.html#aba0b21dde1dcf9a52b6bc0368c3084e2',1,'CodereTvmaze::DAL::DatabaseConnection']]],
  ['dispose_20tt_20method_20tt_9',['Dispose tt method tt',['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md212',1,'Dispose() &lt;tt&gt;method&lt;/tt&gt;'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md347',1,'Dispose() &lt;tt&gt;method&lt;/tt&gt;']]],
  ['dvdcountrycode_20networkid_20webchannelid_20href_20tt_20method_20tt_10',['dvdCountryCode networkId webChannelId href tt method tt',['../md__codere_tvmaze_8_d_a_l_2obj_2_debug_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md252',1,'AddToDatabase(id,url,name,type,language,status,runtime,averageRuntime,premiered,ended,officialSite,weight,summary,updated,previousEpisodeHref,previousEpisodeName,nextEpisodeHref,nextEpisodeName,imageMedium,imageOriginal,average,tvrage,thetvdb,imdb,dvdCountryCode,networkId,webChannelId,href) &lt;tt&gt;method&lt;/tt&gt;'],['../md__codere_tvmaze_8_d_a_l_2obj_2_release_2net8_80_2_codere_tvmaze_8_d_a_l.html#autotoc_md387',1,'AddToDatabase(id,url,name,type,language,status,runtime,averageRuntime,premiered,ended,officialSite,weight,summary,updated,previousEpisodeHref,previousEpisodeName,nextEpisodeHref,nextEpisodeName,imageMedium,imageOriginal,average,tvrage,thetvdb,imdb,dvdCountryCode,networkId,webChannelId,href) &lt;tt&gt;method&lt;/tt&gt;']]]
];
